{% set name = "molecule-generation" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molecule_generation-{{ version }}.tar.gz
  sha256: 30498145d9e5368d57de1c58c48ddb12113e3ca125765a19688b534cb15c6395

build:
  entry_points:
    - molecule_generation = molecule_generation.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - dpu-utils >=0.2.13
    - more-itertools
    - numpy >=1.19.2
    - protobuf >=3.20,<4
    - rdkit
    - scikit-learn >=0.24.1
    - tensorflow >=2.1.0,<3
    - tf2-gnn >=2.13.0

test:
  imports:
    - molecule_generation
  commands:
    - molecule_generation --help

about:
  home: https://github.com/microsoft/molecule-generation/
  summary: Implementations of deep generative models of molecules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
